server:
  address: 0.0.0.0
  tomcat:
    accept-count: 2000 # 수락 대기열을 넉넉히 늘림
    threads:
      max: 200 # 동시에 처리할 스레드 수 (필요시 조절)
    keep-alive-timeout: 60000 # 60초 동안 연결 유지
    max-keep-alive-requests: 1000 # 한 연결당 최대 1000개 요청 허용
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: SA
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

        #dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints: # 1. 여러 엔드포인트를 노출할 때는 복수형(s)을 씁니다.
    web:
      exposure:
        include: prometheus, health, info
  endpoint: # 2. 특정 엔드포인트의 세부 설정을 할 때는 단수형을 씁니다.
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ClothShoppingMall # 그라파나가 찾을 이름표